spring.application.name=sysacademy
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/academia

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Swagger/OpenAPI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.use-root-path=true
springdoc.show-actuator=false